name: Ubuntu 22.04 (clang)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  ASAN_OPTIONS: alloc_dealloc_mismatch=0

jobs:
  build_by_clang:
    strategy:
      matrix:
        mode: [Debug, Release]
        libcxx: [OFF]
        ssl: [OFF]
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get install clang
          sudo apt-get install openssl
          sudo apt-get install libssl-dev

      - name: Configure CMake
        run: CXX=clang++ CC=clang cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.mode}} -DCINATRA_ENABLE_SSL=${{matrix.ssl}} -DBUILD_WITH_LIBCXX=${{matrix.libcxx}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.mode}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.mode}} -j `nproc` -V